version: '2'

networks:
  timporter_network:
    external:
      name: nginxproxynetwork

services:
  esta:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: timbuctoo_importer
    restart: always
    environment:
      - VIRTUAL_HOST=timporter.sd.di.huc.knaw.nl
    ports:
      - 80:80
    networks:
      - timporter_network