version: '2'

networks:
  timporter_network:
    external:
      name: nginxproxynetwork

services:
  timport:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: timbuctoo_importer
    restart: always
    environment:
      - VIRTUAL_HOST=timporter.sd.di.huc.knaw.nl
    volumes:
      - /home/robz/:/home
    ports:
      - 8085:80
    networks:
      - timporter_network